Update .travis.yml
The haxm-darwin Travis build has been failing due to HomeBrew version is out of date. So add the update step to the build script.
Error: Your Homebrew is outdated. Please run `brew update`.
Error: Kernel.exit